version: '3.8'

services:
  #dmit_reports_db:
  #  image: postgres:14
  #  restart: always
  #  ports:
  #    - 5434:5432
  #  environment:
  #    - POSTGRES_DB=reports
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=311034
  #  container_name: dmit_reports_db
  #  volumes:
  #    - ./postgres-data:/var/lib/postgresql/data
  #  networks:
  #    - dmit_network

  dmit_reports_app:
    build:
      context: .
      dockerfile: Dockerfile.reports
    container_name: dmit_reports_app
    networks:
      - dmit_network

networks:
  dmit_network:
    external: true
