version: '3.8'

services:
  dmit_reports_db:
    image: postgres:14
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=reports
      - POSTGRES_USER=reports_user
      - POSTGRES_PASSWORD=311034
    container_name: dmit_reports_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dmit_reports_network

  dmit_reports_app:
    build:
      context: .
      dockerfile: Dockerfile.reports
    env_file:
      - ./.env
    container_name: dmit_reports_app
    depends_on:
      - dmit_reports_db
    networks:
      - dmit_reports_network
  #dmit_reports_nginx:
  #  image: nginx:latest
  #  container_name: dmit_reports_nginx
  #  ports:
  #    - "8888:80"
  #    - "4444:443"
  #  volumes:
  #    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #  depends_on:
  #    - dmit_reports_app
  #  networks:
  #    - dmit_reports_network

networks:
  dmit_reports_network:
