version: '3.8'

services:
  dmit_reports_app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: dmit_reports_app
    depends_on:
      - dmit_reports_db
    networks:dmit_reports:


  dmit_reports_db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: teslodb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
